spring:
  application:
    name: application-observabilidade

management:
  metrics:
    distribution:
      percentiles-histogram:
        http_server_requests: true
  endpoints:
    web:
      exposure:
        include: metrics
  endpoint:
    prometheus:
      access: unrestricted

logging:
  level:
    all: debug